### ISSUE TITLE
add "show" redirect in subscription subscription controller (and path) to show page in the Hub

### ISSUE THREAD

**Issue by waywho** [zaikio/zaikio-oauth_client#319]
Based on the [subscription flow UX design](https://github.com/orgs/zaikio/projects/69/views/1), there needs to be a show subscription path to direct users from an app to the Hub to show their current subscription, so that users can "Manage subscription"

It would make sense to create this in the oauth_client to generate the path.

![185610284-284172c5-7cd5-43ec-8924-04e1b217eb49](https://user-images.githubusercontent.com/7893004/194100614-cc603b22-dfdd-44ef-925b-8e139cc01904.png)

@jalyna wdyt?

**Comment by jalyna** [comment]
@waywho I'm not sure if this has really something todo with the oauth client. In case we want to enhance the link system it might be probably more beneficial to extend hub's API to return those kind of URLs
